require 'cornerstore/api/product'
require 'cornerstore/api/variant'
require 'cornerstore/api/price'
require 'cornerstore/api/property'
require 'cornerstore/api/differentiating_property'
require 'cornerstore/api/image'
require 'cornerstore/api/collection'
require 'cornerstore/api/cart'
require 'cornerstore/api/line_item'
require 'cornerstore/api/search'

require 'cornerstore/api/order'
require 'cornerstore/api/payment_means'
require 'cornerstore/api/cancellation'
require 'cornerstore/api/shipment'
require 'cornerstore/api/carrier'
require 'cornerstore/api/address'
require 'cornerstore/api/customer'
